<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<UseWPF>true</UseWPF>
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="8.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="ClickerGameWindow.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Page Remove="ClickerGameWindow.xaml" />
	</ItemGroup>
</Project>